### ISSUE TITLE
Pretrained model weight error

### ISSUE THREAD

**Issue by DUT-CSJ** [AIVResearch/MSANet#12]
The pretrained model weight of PSPNet on coco split1 seems broken, please update new weight.
Thank you!

**Comment by Ehteshamciitwah** [comment]
I downloaded the base learner weight successfully. Please try again. Thank you

**Comment by DUT-CSJ** [comment]
Sorry, I didn't describe the problem clearly.
Only the ResNet101 of coco split1 seems broken.
It can be downloaded, but it is different from other resnet101 weights.
Please check it again, thank you!
