### ISSUE TITLE
Training script

### ISSUE THREAD

**Issue by yswang1717** [AIVResearch/MSANet#4]
Hello, 
Thanks for your great contribution in FS field. 
I've seen your code, however, there is not training script. 
Could you please upload the training script and configuration file?

**Comment by SirojbekSafarov** [comment]
Sorry for the delay. test code is provided to validate the model. However, the training file will be shared soon after the paper decision.

**Comment by moonsh** [comment]
@SirojbekSafarov The training file will be updated soon?
