### ISSUE TITLE
Trsaining base model

### ISSUE THREAD

**Issue by aminpdik** [AIVResearch/MSANet#7]
Hello

Thanks for the great work and for sharing the code.

I have one question regarding the training base model. Have you trained Resnet 101 base model considering the unseen classes as background same as BAM?

Thanks

**Comment by Ehteshamciitwah** [comment]
We use the pre-trained model provided by BAM. As the main focus was on the Meta Learner part. Yes, you are right the base learner is trained only on bass class assuming novel as background.

**Comment by aminpdik** [comment]
Thanks for your response.

BAM just provided weights for VGG and Resnet50. I think you trained in the same way as BAM for Resnet 101.

**Comment by aminpdik** [comment]
Hi @Ehteshamciitwah 

Can I get the answer to my last question? BAM only provided weight for RESnet50 but you also provided RESnet101. Did you train the same as BAM for resnet101?

Best

**Comment by Ehteshamciitwah** [comment]
Sorry for the delay.  yes, we trained base learner for ResNet 101 following BAM. The weights of ResNet101 are also provided.

**Comment by aminpdik** [comment]
Thank you for your answer
